[package]
name = "canum"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = ["canum_*"]

[dependencies]
avian2d = {
  version = "0.6.1",
  default-features = false,
  features = [
    "default-collider",
    "2d",
    "debug-plugin",
    "f32",
    "parallel",
    "parry-f32",
  ]
}
bevy = {
  version = "0.18.1",
  default-features = false,
  features = [
    "2d",
    "debug",
    "dynamic_linking",
    "mp3",
    "multi_threaded",
    "wav",
  ]
}
bevy_image_font = "0.11.0"
canum_addons = { path = "canum_addons" }
canum_fx = { path = "canum_fx" }
canum_play = { path = "canum_play" }
canum_res = { path = "canum_res" }
canum_s1 = { path = "canum_s1" }
canum_s2 = { path = "canum_s2" }
canum_save = { path = "canum_save" }
canum_ui = { path = "canum_ui" }
rand = "0.10.1"
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }

[profile.dev]
opt-level = 1
